version: '3.6'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    volumes:
    - db_data:/var/lib/postgresql/data
    - .:/app
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
    - "5432:5432"
    networks:
    - local_network
  nextjs:
    image: node:18.19.1-buster
    container_name: nextjs
    command: bash -c "yarn prisma:migrate && yarn dev"
    working_dir: /app
    volumes:
    - .:/app
    environment:
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
    ports:
    - "3000:3000"
    depends_on:
    - "postgres"
    networks:
    - local_network
volumes:
  db_data:
networks:
  local_network:
